# Generated by Django 5.2.7 on 2025-10-25 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_options_alter_news_options_news_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('match', 'Match'), ('exclusive', 'Exclusive'), ('update', 'Update'), ('analysis', 'Analysis'), ('rumor', 'Rumor'), ('transfer', 'Transfer')], default='update', max_length=20),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='news_commen_created_8567bd_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['news', 'created_at'], name='news_commen_news_id_30bb08_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-created_at'], name='news_news_created_33ef44_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category', '-created_at'], name='news_news_categor_5b8b50_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='news_news_slug_915ecd_idx'),
        ),
    ]
