# Generated by Django 5.2.7 on 2025-10-22 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('gk gloves', 'GK Gloves'), ('ball', 'Ball'), ('jacket', 'Jacket'), ('scarf', 'Scarf')], default='jersey', max_length=20)),
                ('price', models.IntegerField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('product_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
