# Generated by Django 5.2.7 on 2025-11-24 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('gk gloves', 'GK Gloves'), ('ball', 'Ball'), ('jacket', 'Jacket'), ('scarf', 'Scarf')], default='jersey', max_length=20)),
                ('price', models.IntegerField()),
                ('thumbnail', models.URLField(default='https://example.com/image.jpg')),
                ('product_link', models.URLField(default='https://example.com')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
