# Generated by Django 5.2.7 on 2025-10-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Merch',
        ),
    ]
