# Generated by Django 5.2.7 on 2025-10-26 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_rename_news_merch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merch',
            name='product_link',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='thumbnail',
            field=models.URLField(default='https://example.com/image.jpg'),
        ),
    ]
