# Generated by Django 5.2.7 on 2025-11-24 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('posisi', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=10)),
                ('klub', models.CharField(max_length=100)),
                ('umur', models.PositiveIntegerField()),
                ('market_value', models.DecimalField(decimal_places=2, help_text='Dalam juta Euro (€)', max_digits=10)),
                ('foto', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
