# Generated by Django 5.2.7 on 2025-11-24 06:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegendPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Kiper', 'Kiper'), ('Bek', 'Bek'), ('Gelandang', 'Gelandang'), ('Penyerang', 'Penyerang')], max_length=20)),
                ('is_legend', models.BooleanField(default=True)),
                ('club', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
