# Generated by Django 5.2.7 on 2025-10-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileLegend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legendplayer',
            name='market_value',
        ),
    ]
