# Generated by Django 5.2.7 on 2025-10-22 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileLegend', '0002_remove_legendplayer_market_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legendplayer',
            options={'ordering': ['name'], 'verbose_name': 'Legend Player', 'verbose_name_plural': 'Legend Players'},
        ),
        migrations.AddField(
            model_name='legendplayer',
            name='is_legend',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='legendplayer',
            name='position',
            field=models.CharField(choices=[('Kiper', 'Kiper'), ('Bek', 'Bek'), ('Gelandang', 'Gelandang'), ('Penyerang', 'Penyerang')], max_length=50),
        ),
        migrations.AlterField(
            model_name='legendplayer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
