# Generated by Django 5.2.7 on 2025-10-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileLegend', '0003_alter_legendplayer_options_legendplayer_is_legend_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legendplayer',
            options={},
        ),
        migrations.RemoveField(
            model_name='legendplayer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='legendplayer',
            name='current_club',
        ),
        migrations.RemoveField(
            model_name='legendplayer',
            name='user',
        ),
        migrations.AddField(
            model_name='legendplayer',
            name='club',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legendplayer',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legendplayer',
            name='position',
            field=models.CharField(choices=[('Kiper', 'Kiper'), ('Bek', 'Bek'), ('Gelandang', 'Gelandang'), ('Penyerang', 'Penyerang')], max_length=20),
        ),
    ]
