# Generated by Django 5.2.7 on 2025-11-24 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertandingan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jenis_pertandingan', models.CharField(blank=True, choices=[('kualifikasi piala dunia', 'Kualifikasi Piala Dunia'), ('pertandingan persahabatan', 'Pertandingan Persahabatan'), ('piala asean', 'Piala ASEAN'), ('piala asia', 'Piala Asia')], max_length=100, null=True, verbose_name='Jenis Pertandingan')),
                ('tim_tuan_rumah', models.CharField(blank=True, max_length=100, null=True)),
                ('tim_tamu', models.CharField(blank=True, max_length=100, null=True)),
                ('bendera_tuan_rumah', models.URLField(blank=True, max_length=500, null=True, verbose_name='Bendera Tuan Rumah')),
                ('bendera_tamu', models.URLField(blank=True, max_length=500, null=True, verbose_name='Bendera Tamu')),
                ('tanggal', models.CharField(blank=True, max_length=100, null=True)),
                ('stadion', models.CharField(blank=True, max_length=100, null=True)),
                ('skor_tuan_rumah', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('skor_tamu', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pencetak_gol_tuan_rumah', models.TextField(blank=True, null=True)),
                ('pencetak_gol_tamu', models.TextField(blank=True, null=True)),
                ('starter_tuan_rumah', models.TextField(blank=True, null=True)),
                ('starter_tamu', models.TextField(blank=True, null=True)),
                ('pengganti_tuan_rumah', models.TextField(blank=True, null=True)),
                ('pengganti_tamu', models.TextField(blank=True, null=True)),
                ('manajer_tuan_rumah', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Manajer Tuan Rumah')),
                ('manajer_tamu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Manajer Tamu')),
                ('highlight', models.URLField(blank=True, null=True, verbose_name='Highlight')),
                ('penguasaan_bola_tuan_rumah', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('penguasaan_bola_tamu', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tembakan_tuan_rumah', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tembakan_tamu', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('on_target_tuan_rumah', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('on_target_tamu', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('akurasi_umpan_tuan_rumah', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('akurasi_umpan_tamu', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pelanggaran_tuan_rumah', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pelanggaran_tamu', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kartu_kuning_tuan_rumah', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kartu_kuning_tamu', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kartu_merah_tuan_rumah', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kartu_merah_tamu', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('offside_tuan_rumah', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('offside_tamu', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('corner_tuan_rumah', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('corner_tamu', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pertandingan Internasional',
                'ordering': ['-tanggal'],
            },
        ),
    ]
