# Generated by Django 5.2.7 on 2025-10-22 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPemainLaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=False, help_text='Centang jika pemain ini adalah bagian dari Starting XI')),
            ],
            options={
                'verbose_name_plural': 'Detail Pemain Per Laga',
            },
        ),
        migrations.CreateModel(
            name='Manajer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Manajer',
            },
        ),
        migrations.CreateModel(
            name='Pemain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('posisi', models.CharField(blank=True, choices=[('GK', 'Kiper'), ('DF', 'Bek'), ('MF', 'Gelandang'), ('FW', 'Penyerang')], max_length=2, null=True)),
                ('umur', models.PositiveIntegerField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_pemain_legend', models.BooleanField(default=False)),
                ('tahun_bermain', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Pemain',
            },
        ),
        migrations.CreateModel(
            name='Pertandingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('stadion', models.CharField(blank=True, max_length=100, null=True)),
                ('skor_tuan_rumah', models.PositiveIntegerField(blank=True, null=True)),
                ('skor_tamu', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pertandingan',
                'ordering': ['-tanggal_waktu'],
            },
        ),
        migrations.CreateModel(
            name='StatistikTimPertandingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tembakan', models.PositiveIntegerField(default=0)),
                ('tembakan_ke_gawang', models.PositiveIntegerField(default=0)),
                ('penguasaan_bola', models.PositiveIntegerField(default=0, help_text='Persentase, misal: 55')),
                ('pelanggaran', models.PositiveIntegerField(default=0)),
                ('kartu_kuning', models.PositiveIntegerField(default=0)),
                ('kartu_merah', models.PositiveIntegerField(default=0)),
                ('offside', models.PositiveIntegerField(default=0)),
                ('tendangan_sudut', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Statistik Tim Pertandingan',
            },
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('daftar_pemain', models.ManyToManyField(blank=True, related_name='tim_dibela', to='match.pemain')),
                ('staf_manajer', models.ManyToManyField(blank=True, related_name='tim_dilatih', to='match.manajer')),
            ],
            options={
                'verbose_name_plural': 'Tim',
            },
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='detailpemainlaga',
            name='pemain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_laga', to='match.pemain'),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='pemain_bermain',
            field=models.ManyToManyField(blank=True, related_name='laga_dimainkan', through='match.DetailPemainLaga', to='match.pemain'),
        ),
        migrations.AddField(
            model_name='detailpemainlaga',
            name='pertandingan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pemain', to='match.pertandingan'),
        ),
        migrations.AddField(
            model_name='statistiktimpertandingan',
            name='pertandingan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistik_tim', to='match.pertandingan'),
        ),
        migrations.AddField(
            model_name='statistiktimpertandingan',
            name='tim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistik_laga', to='match.tim'),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='tim_tamu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laga_tandang', to='match.tim'),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='tim_tuan_rumah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laga_kandang', to='match.tim'),
        ),
        migrations.AddField(
            model_name='detailpemainlaga',
            name='tim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.tim'),
        ),
        migrations.AlterUniqueTogether(
            name='statistiktimpertandingan',
            unique_together={('pertandingan', 'tim')},
        ),
        migrations.AlterUniqueTogether(
            name='detailpemainlaga',
            unique_together={('pertandingan', 'pemain')},
        ),
    ]
