# Generated by Django 5.2.7 on 2025-10-23 01:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_detailpemainlaga_manajer_pemain_pertandingan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemain',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
