# Generated by Django 5.2.7 on 2025-10-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_pemain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertandingan',
            name='highlights_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
