# Generated by Django 5.2.7 on 2025-10-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_pertandingan_highlights_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemain',
            name='tahun_bermain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
