# Generated by Django 5.2.7 on 2025-10-23 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_pemain_tahun_bermain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tim',
            name='staf_manajer',
        ),
        migrations.AlterUniqueTogether(
            name='statistiktimpertandingan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='statistiktimpertandingan',
            name='pertandingan',
        ),
        migrations.RemoveField(
            model_name='statistiktimpertandingan',
            name='tim',
        ),
        migrations.AlterModelOptions(
            name='detailpemainlaga',
            options={'ordering': ['pertandingan', 'tim', '-is_starter', 'pemain__nama'], 'verbose_name_plural': 'Detail Pemain Per Laga'},
        ),
        migrations.AlterModelOptions(
            name='pemain',
            options={'ordering': ['nama'], 'verbose_name_plural': 'Pemain'},
        ),
        migrations.AlterModelOptions(
            name='pertandingan',
            options={'ordering': ['-tanggal_waktu'], 'verbose_name_plural': 'Pertandingan Internasional'},
        ),
        migrations.AlterModelOptions(
            name='tim',
            options={'verbose_name_plural': 'Tim Nasional'},
        ),
        migrations.RemoveField(
            model_name='pertandingan',
            name='highlights_url',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='daftar_pemain',
        ),
        migrations.AddField(
            model_name='pemain',
            name='market_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Market Value'),
        ),
        migrations.AddField(
            model_name='pemain',
            name='nama_klub',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Klub'),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='highlight_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Highlight'),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='jenis_pertandingan',
            field=models.CharField(blank=True, choices=[('kualifikasi piala dunia', 'Kualifikasi Piala Dunia'), ('pertandingan persahabatan', 'Pertandingan Persahabatan'), ('piala asean', 'Piala ASEAN'), ('piala asia', 'Piala Asia')], max_length=100, null=True, verbose_name='Jenis Pertandingan'),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='kartu_kuning_tamu_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='kartu_kuning_tuan_rumah_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='kartu_merah_tamu_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='kartu_merah_tuan_rumah_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='manajer_tamu_nama',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Manajer Tamu'),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='manajer_tuan_rumah_nama',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Manajer Tuan Rumah'),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='pencetak_gol_tamu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='pencetak_gol_tuan_rumah',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tim',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tim',
            name='rank_fifa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailpemainlaga',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pemain',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto Profil'),
        ),
        migrations.AlterField(
            model_name='pemain',
            name='nama',
            field=models.CharField(max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='pemain',
            name='posisi',
            field=models.CharField(blank=True, choices=[('GK', 'Kiper'), ('DF', 'Bek'), ('MF', 'Gelandang'), ('FW', 'Penyerang')], max_length=2, null=True, verbose_name='Posisi'),
        ),
        migrations.AlterField(
            model_name='pemain',
            name='tahun_bermain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rentang Timnas'),
        ),
        migrations.AlterField(
            model_name='pemain',
            name='umur',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Umur'),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tim',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Manajer',
        ),
        migrations.DeleteModel(
            name='StatistikTimPertandingan',
        ),
    ]
