# Generated by Django 5.2.7 on 2025-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_remove_tim_staf_manajer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertandingan',
            name='pemain_bermain',
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='tim_tamu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='tim_tuan_rumah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelOptions(
            name='pertandingan',
            options={'ordering': ['-tanggal'], 'verbose_name_plural': 'Pertandingan Internasional'},
        ),
        migrations.RenameField(
            model_name='pertandingan',
            old_name='highlight_url',
            new_name='highlight',
        ),
        migrations.RenameField(
            model_name='pertandingan',
            old_name='manajer_tamu_nama',
            new_name='manajer_tamu',
        ),
        migrations.RenameField(
            model_name='pertandingan',
            old_name='manajer_tuan_rumah_nama',
            new_name='manajer_tuan_rumah',
        ),
        migrations.RemoveField(
            model_name='pertandingan',
            name='kartu_kuning_tamu_str',
        ),
        migrations.RemoveField(
            model_name='pertandingan',
            name='kartu_kuning_tuan_rumah_str',
        ),
        migrations.RemoveField(
            model_name='pertandingan',
            name='kartu_merah_tamu_str',
        ),
        migrations.RemoveField(
            model_name='pertandingan',
            name='kartu_merah_tuan_rumah_str',
        ),
        migrations.RemoveField(
            model_name='pertandingan',
            name='tanggal_waktu',
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='akurasi_umpan_tamu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='akurasi_umpan_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='bendera_tamu',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Bendera Tamu'),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='bendera_tuan_rumah',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Bendera Tuan Rumah'),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='corner_tamu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='corner_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='kartu_kuning_tamu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='kartu_kuning_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='kartu_merah_tamu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='kartu_merah_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='offside_tamu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='offside_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='on_target_tamu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='on_target_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='pelanggaran_tamu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='pelanggaran_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='pengganti_tamu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='pengganti_tuan_rumah',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='penguasaan_bola_tamu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='penguasaan_bola_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='starter_tamu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='starter_tuan_rumah',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='tanggal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='tembakan_tamu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pertandingan',
            name='tembakan_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DetailPemainLaga',
        ),
        migrations.DeleteModel(
            name='Pemain',
        ),
        migrations.DeleteModel(
            name='Tim',
        ),
    ]
