# Generated by Django 5.2.7 on 2025-10-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_remove_pertandingan_pemain_bermain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertandingan',
            name='akurasi_umpan_tamu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='akurasi_umpan_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='corner_tamu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='corner_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='highlight',
            field=models.URLField(blank=True, null=True, verbose_name='Highlight'),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='kartu_kuning_tamu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='kartu_kuning_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='kartu_merah_tamu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='kartu_merah_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='offside_tamu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='offside_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='on_target_tamu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='on_target_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='pelanggaran_tamu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='pelanggaran_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='penguasaan_bola_tamu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='penguasaan_bola_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='skor_tamu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='skor_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='tembakan_tamu',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pertandingan',
            name='tembakan_tuan_rumah',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
